### ISSUE TITLE
Buying "Experience Multiplier" for cheaper than it costs

### ISSUE THREAD

**Issue by mloft74** [Septimis/rock-paper-scissors#6]
You can buy "Experience Multiplier" multiple times in one shop visit, so you can get "Experience Bonus: 4" buy buying "Experience Multiplier: 2" twice for the total price of 50 xp instead of "Experience Multiplier: 4" once for the price of 75 xp.

Steps to reproduce:
* Have at least 50 xp
* Buy "Experience Multiplier: 2"
* Buy "Experience Multiplier: 2" again
* Observe that you now have "Experience Bonus: 4" with 50 less xp instead of 75 less xp

**Comment by Septimis** [comment]
Fixed.
Old: Initial x2 was 25 xp (12.5xp per multiple) and every multiple after that was 25xp each
New: Each x2 is now 15 xp.
